backend:
  name: github
  repo: yhisato-sys/practice-site # ← あなたのリポジトリ
  branch: main # ← メインブランチ
  auth_type: implicit # ← ログイン方式をGitHubに
  app_id: Ov23lipSH3b6B1q4yA5T # ← GitHub OAuth 公開クライアントID（共通でOK）

publish_mode: editorial_workflow

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "新着情報"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }
