backend:
  name: github
  repo: yhisato-sys/practice-site
  branch: main
  auth_type: github
  app_id: 0v231ipSH3b6B1q4yA5T
  base_url: https://yhisato-sys.github.io/practice-site
  auth_endpoint: auth

publish_mode: editorial_workflow

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "新着情報"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }
